/**
 * Makes a brand-new entry render as an editable page, on every template.
 *
 * An entry created in Visual Editor holds only the fields someone has typed
 * into. Every other field is ABSENT from the JSON, not empty, and two things
 * follow from that, on any Studio template:
 *
 *   1. Studio resolves a bound prop with `get(data, path, default)`, so an
 *      absent field falls back to the component's registration default. The
 *      page fills with "Your text here", "Read more" and the like.
 *   2. Edit tags are generated by walking the entry's keys. An absent field has
 *      no key, so it gets no `data-cslp`, and Visual Editor cannot select it:
 *      it can only be filled in from the form panel.
 *
 * `fetchTemplateEntry` is the SDK's hook for exactly this point: it runs after
 * the entry is fetched and before the SDK adds the edit tags. Here it fetches
 * the entry the normal way, then gives every field in the content type schema
 * an empty value of the right shape. Existing values are never touched. Empty
 * strings render as nothing (no default kicks in), every field gets its tag,
 * and studio/editor-hints.ts makes empty tagged fields visible inside the editor.
 *
 * It is a no-op for a fully filled entry, so it is on for visitors too: a field
 * an editor deliberately left blank renders blank, never a palette default.
 */
import type { TemplateEntryFetcher } from '@contentstack/studio-client';
import { apiKey, deliveryToken, environment, deliveryHost } from '@/lib/stack';

type Field = {
  uid: string;
  data_type: string;
  multiple?: boolean;
  schema?: Field[];
  blocks?: { uid: string; schema?: Field[] }[];
};
type Obj = Record<string, unknown>;

/** The empty value for one field, shaped so every renderer accepts it. */
function emptyValue(field: Field): unknown {
  if (field.multiple) return [];
  switch (field.data_type) {
    case 'text':
      return '';
    case 'boolean':
      return false;
    case 'link':
      return { title: '', href: '' };
    case 'file':
      // Images bind `image.url`, so the tag needs a `url` key to exist. The
      // empty url renders Studio's placeholder picture, now clickable.
      return { url: '' };
    case 'group':
    case 'global_field':
      return fill({}, field.schema);
    case 'blocks':
    case 'reference':
    case 'taxonomy':
      return [];
    default:
      // number, isodate, json (JSON RTE): `null`, not a fake value. It is
      // present, so it is tagged, but no renderer mistakes it for content.
      return null;
  }
}

/** Fills absent fields in place, recursing into groups and modular blocks. */
function fill(target: Obj, schema: Field[] = []): Obj {
  for (const field of schema) {
    const value = target[field.uid];
    // `null` counts as empty too: a draft sends a cleared image as `null`, and
    // `image.url` cannot be tagged on null.
    if (value === undefined || value === null) {
      target[field.uid] = emptyValue(field);
      continue;
    }
    if (field.data_type === 'group' || field.data_type === 'global_field') {
      for (const item of field.multiple ? (value as Obj[]) : [value as Obj]) {
        if (item && typeof item === 'object') fill(item, field.schema);
      }
    }
    // A block added from Visual Editor arrives as `{ block_uid: {...} }` with
    // only what was typed: fill it against that block's own schema.
    if (field.data_type === 'blocks' && Array.isArray(value)) {
      for (const item of value as Obj[]) {
        for (const block of field.blocks ?? []) {
          const inner = item?.[block.uid];
          if (inner && typeof inner === 'object') fill(inner as Obj, block.schema);
        }
      }
    }
  }
  return target;
}

// One schema request per content type per process; schemas change on deploy.
const schemas = new Map<string, Promise<Field[] | null>>();

function schemaFor(contentTypeUid: string) {
  if (!schemas.has(contentTypeUid)) {
    const url =
      `https://${deliveryHost}/v3/content_types/${contentTypeUid}` +
      // Without this flag Global Fields arrive with no schema to fill from.
      `?environment=${environment}&include_global_field_schema=true`;
    const request = fetch(url, {
      headers: { api_key: apiKey, access_token: deliveryToken },
      // Cached in memory above; Next's data cache would outlive a schema change.
      cache: 'no-store',
    })
      .then((res) => (res.ok ? res.json() : null))
      .then((body) => (body?.content_type?.schema as Field[]) ?? null)
      .catch(() => null);
    schemas.set(contentTypeUid, request);
    // A failed lookup is retried on the next request instead of being cached.
    request.then((schema) => schema ?? schemas.delete(contentTypeUid));
  }
  return schemas.get(contentTypeUid)!;
}

export const fetchTemplateEntry: TemplateEntryFetcher = async ({
  connectedContentType,
  defaultFetch,
}) => {
  const entry = await defaultFetch();
  if (!entry || !connectedContentType) return entry;
  // Never let a missing schema break a page: render the entry as fetched.
  const schema = await schemaFor(connectedContentType);
  return schema ? fill(entry, schema) : entry;
};
