/**
 * Project constants + a tiny .env reader/writer.
 *
 * No dotenv dependency: this reads the one file it owns. The provisioning
 * scripts write ids back here so the app and the later scripts agree.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const ENV_PATH = path.join(ROOT, '.env');

export function readEnv() {
  if (!fs.existsSync(ENV_PATH)) return {};
  return Object.fromEntries(
    fs
      .readFileSync(ENV_PATH, 'utf8')
      .split('\n')
      .map((l) => l.trim())
      .filter((l) => l && !l.startsWith('#'))
      .map((l) => {
        const i = l.indexOf('=');
        return [l.slice(0, i), l.slice(i + 1)];
      }),
  );
}

export function writeEnv(values) {
  const merged = { ...readEnv(), ...values };
  const body = [
    '# Generated by the provisioning scripts — safe to re-generate.',
    '# Never commit this file. See .env.example for the shape.',
    '',
    ...Object.entries(merged)
      .filter(([, v]) => v !== undefined && v !== '')
      .map(([k, v]) => `${k}=${v}`),
    '',
  ].join('\n');
  fs.writeFileSync(ENV_PATH, body);
}

const env = { ...readEnv(), ...process.env };

// ─── Project constants ───────────────────────────────────────────────────────
export const STACK_API_KEY = env.NEXT_PUBLIC_CONTENTSTACK_API_KEY ?? env.CS_API_KEY ?? '';
export const ENVIRONMENT = env.NEXT_PUBLIC_CONTENTSTACK_ENVIRONMENT ?? 'preview';
/**
 * URL prefix → stack locale code, e.g. `en:en-us,fr:fr-fr`. Same variable, same
 * format as lib/locales.ts reads in the app. The first entry is the default and
 * must be the stack's master locale: the sample content is seeded and published
 * in it (LOCALE below).
 */
export const LOCALES = Object.fromEntries(
  (env.NEXT_PUBLIC_CONTENTSTACK_LOCALES || 'en:en-us')
    .split(',')
    .map((pair) =>
      pair
        .trim()
        .split(':')
        .map((s) => s.trim()),
    )
    .filter(([prefix, code]) => prefix && code),
);
export const LOCALE = Object.values(LOCALES)[0];
/**
 * The environment's Base URL. Studio composes the canvas iframe address as
 * Base URL + Canvas URL, and Studio itself is served over HTTPS — so an
 * http://localhost base URL is blocked as mixed content and the canvas stays
 * blank with nothing in the UI to explain why. Hence https by default; the dev
 * script generates a locally-trusted certificate to match.
 */
export const BASE_URL = env.NEXT_PUBLIC_BASE_URL ?? 'https://localhost:3000';

/** Studio's own content type. One per project; the project points at it by uid. */
export const COMPOSITIONS_CT = 'compositions';
export const STUDIO_PROJECT_NAME = 'Studio Boilerplate';
export const CANVAS_URL = '/canvas';

export const ENVIRONMENT_UID = env.CONTENTSTACK_ENVIRONMENT_UID ?? '';
export const STUDIO_PROJECT_UID = env.STUDIO_PROJECT_UID ?? '';

if (!STACK_API_KEY) {
  throw new Error(
    'No stack API key. Set NEXT_PUBLIC_CONTENTSTACK_API_KEY in .env (copy .env.example).',
  );
}
